name: screenshotbase
description: Dart client for Screenshotbase API to render website screenshots and PDFs. See https://screenshotbase.com
version: 0.1.0
homepage: https://screenshotbase.com
repository: https://github.com/martechdev/screenshotbase-dart
environment:
  sdk: '>=2.19.0 <4.0.0'
dependencies:
  http: ^1.2.0
dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
